### ISSUE TITLE
additional import necessary to build SmartPi from scratch

### ISSUE THREAD

**Issue by Epposan** [nDenerserve/SmartPi#10]
In order to succesfully build SmartPi from scratch, I needed to additionally import the `i2c` library like:
`go get golang.org/x/exp/io/i2c`

I am running `Raspbian GNU/Linux 8 (jessie)`

Maybe you want to update `Build_SmartPi_from_Scratch.txt`

**Comment by SuperQ** [comment]
Another option would be to use [govendor](https://github.com/kardianos/govendor) to include these.
