### ISSUE TITLE
How do I increase the time between MQTT publish intervals?

### ISSUE THREAD

**Issue by robinsamuel** [nDenerserve/SmartPi#101]

**Comment by StohanzlMart** [comment]
I'd be also interested in the answer, how to OR AT LEAST WHERE!!!!!!!!! modify the MQTT stuff

**Comment by StohanzlMart** [comment]
https://github.com/nDenerserve/SmartPi/search?q=mqtt

reveals one ought to

```sudo find / -iname smartpi```

to reveal that you have to

```sudo nano /etc/smartpi```

Well idk how "open source" devs who sell proprietary hardware come to think a forum (which they mostly ignore) and some source code documentation replaces a "manual"?

For Pete sake, please write on your homepage, that you are providing a free smartPi in exchange for a bachelors or master thesis that writes such a manual.

I get that developing > documenting for you but I see it as an antipattern :(

**Comment by StohanzlMart** [comment]
Once you know about the term "samplerate" you can search on the forum and find:

https://forum.enerserve.eu/showthread.php?tid=1343&pid=4401&highlight=samplerate#pid4401

**Comment by StohanzlMart** [comment]
@robinsamuel can you please close this issue if this helped you?

**Comment by StohanzlMart** [comment]
as it seems 1(Hz) is min-samplerate
