### ISSUE TITLE
Systemd integration does not work properly

### ISSUE THREAD

**Issue by dandjo** [nDenerserve/SmartPi#110]
When I try to stop the services via `sudo service smartpi stop` the services won't stop. I suggest a proper integration of the services with systemd as described in this thread: [Systemd Service funktioniert nicht](https://forum.enerserve.eu/showthread.php?tid=1418)
The idea was to setup multiple services for each binary with proper dependencies and user rights. As far as I tested so far, my solution is working fine.

**Comment by nD-enerserve** [comment]
Fixed
