### ISSUE TITLE
Mobile webinterface is difficult to read

### ISSUE THREAD

**Issue by dandjo** [nDenerserve/SmartPi#112]
The floating of the cards is not optimal on smartphones. Suggestion: stack the cards on top of each other.

![Screenshot_20201001_185336](https://user-images.githubusercontent.com/34278179/94839790-c6bd8480-0417-11eb-930b-8989f273eea5.png)

**Comment by dandjo** [comment]
Are there any efforts to improve this? 2 years, no reaction.

**Comment by Adminius** [comment]
Hi @dandjo 
try this:
[mobile.zip](https://github.com/nDenerserve/SmartPi/files/9605159/mobile.zip)
extract this html file to /var/smartpi/www
and call this new page with http://smartPi-IP/mobile.html

alternatively: remove index.html and rename mobile.html to index.html, but mobile.html looks not good on big screens :/

![image](https://user-images.githubusercontent.com/17052262/191196072-65fde425-a47b-41d2-925b-c77321ad11a4.png)

**Comment by nD-enerserve** [comment]
In end of january we have a new GUI
