### ISSUE TITLE
NODE-RED-NODE-SMARTPI doesn't work

### ISSUE THREAD

**Issue by schurick1502** [nDenerserve/SmartPi#114]
Hello,
I've a problem with my Smartpi (NODE-RED) .
It now doesn't work after install of a new package (for example "Dashboard").
What i can do?
Here any screenshots of my problem.
Help meeeeeeeeee.

Alex
![Unbenannt](https://user-images.githubusercontent.com/81833470/113457479-266d0a80-9410-11eb-9aa9-9c617926d9d1.PNG)
I tried to copy the files in node_modules/node-red-node-smartpi.
Now it's possible to choose the smartpi ( only two) but there is no values.
![Unbenannt2](https://user-images.githubusercontent.com/81833470/113458271-1a824800-9412-11eb-91af-4a6b7c68db53.PNG)
![Unbenannt3](https://user-images.githubusercontent.com/81833470/113458277-1d7d3880-9412-11eb-8700-728d3d5d5dc5.PNG)
![Unbenannt4](https://user-images.githubusercontent.com/81833470/113458286-24a44680-9412-11eb-9ca2-4d352335315c.PNG)

**Comment by MrLaffer** [comment]
Can you show your smartpi-input.js and look wether watch and fs.readFile points to /var/tmp/smartpi/smartpi_values.
Post cat /var/tmp/smartpi/smartpi_values

**Comment by MrLaffer** [comment]
Now the Smart-Input Node is also available at npmjs (https://www.npmjs.com/package/node-red-smartpi).
To install, either go to the directory ~/.node-red and call npm i node-red-smartpi or install in the graphical interface of nodered.
