### ISSUE TITLE
Add Prometheus support

### ISSUE THREAD

**Issue by SuperQ** [nDenerserve/SmartPi#12]
Prometheus[0] is a time-series based monitoring system.  It uses a simple metrics format over http to export and collect data.

I am considering writing this support for the SmartPi using the supported client library[1].

[0]: https://prometheus.io/
[1]: https://github.com/prometheus/client_golang

**Comment by pberndro** [comment]
take a look at my exporter, will be finished in a few days.
https://github.com/pberndro/smartpi_exporter

**Comment by SuperQ** [comment]
Cool, rather than poke at the REST API, it would be better to export this data directly from the SmartPi server binary.

**Comment by pberndro** [comment]
would be nice but i think it's more a task for the @nD-enerserve team or feel free to send a PR.
Now my exporter is ready for testing, let me know when you have feedback. a readme is upcomming.

**Comment by nD-enerserve** [comment]
Hello,
that looks good. Next week we are back for developing and I will integrate it.

**Comment by SuperQ** [comment]
This is fixed via https://github.com/nDenerserve/SmartPi/pull/40
