### ISSUE TITLE
Database path is not changable

### ISSUE THREAD

**Issue by ChristianEbnoether** [nDenerserve/SmartPi#126]
Hi enerserver
I'm a Fan of your Product, but for me, the question is why there is no GUI way to change the Path to the influxDB directly over the GUI, I have two setups running where I have onsite where the smartpi is installed a running Timeseries Database, with this I don't like to store data directly on an sd card, my goal is to feed the data as fast as it is possible to another performant database.

Of course, you have added a way over MQTT, but why not add a GUI Variable directly to allow the customer to add his own 
DB?

https://github.com/nDenerserve/SmartPi/blob/0f7f61f968f80aaa7fb3f0d4e5244b8669e8937a/src/smartpi/influxdatabase.go#L28

**Comment by nD-enerserve** [comment]
In end of january we have a complete new GUI. Then the database path is changable in the GUI.

**Comment by nD-enerserve** [comment]
![screenshot_smartpi_database_settings](https://github.com/user-attachments/assets/001df33e-ebc5-4d6f-9e35-cae0b1c74bbb)
