### ISSUE TITLE
config file not updated

### ISSUE THREAD

**Issue by Trickx** [nDenerserve/SmartPi#14]
The configuration file located at  SmartPi/config/etc/smartpi seems not to be up to date.
E.g. the item p.Databasefile = cfg.Section("database").Key("file").String()
point to file="smartpi.**rrd**"

rrd for sqlite?

**Comment by nD-enerserve** [comment]
For sqlite, the database file is automatically generated. File name smartpi_logdata_YYYYMM.db. Only the path is used. Therefore, the entry is deleted in one of the next versions.
