### ISSUE TITLE
smartpireadout illegal instruction

### ISSUE THREAD

**Issue by Epposan** [nDenerserve/SmartPi#15]
Unfamiliar with golang, I wonder whether anyone has a clue where to start looking for the reason why smartpireadout only runs for a limited amount of time, terminating with a SIGILL: illegal instruction.

Please see the attached screen log containing two of those occurences.

Thanks.

[smartpireadout-error.txt](https://github.com/nDenerserve/SmartPi/files/799453/smartpireadout-error.txt)

**Comment by nD-enerserve** [comment]
There is a problem in version < 0.5.5 if the sqlfile exist but not the table in the file. Please remove the file from /var/smartpi/db or copy the actual binaries from the github/bin to /usr/local/lib.
The best way is to download the actual version from:
http://blog.enerserve.eu/category/smartpi/installation-smartpi/

http://files.enerserve.eu/smartpi/smartpi_0.5.6.deb

**Comment by Epposan** [comment]
I have tried to run the 0.5.6 version using the image from [http://files.enerserve.eu/smartpi/2017-02-21_raspbian-jessie_smartpi.7z](url), but unfortunately get similar results.

Please see the attached log of events during the first login after having adjusted the filesystem running raspi-config. The initial `ps -ef` is executed only a few seconds after (re-)boot/login. The page at `<ip-adress>:1080` only gets a few updates before it remains static.

[smartpireadout-error-2.txt](https://github.com/nDenerserve/SmartPi/files/803057/smartpireadout-error-2.txt)

**Comment by nD-enerserve** [comment]
Hello,
can you make your smartpi (ssh) accessible via internet?
I would like to look on your smartpi.
Best regards Jens


Am Montag, 27. Februar 2017, 01:04:02 CET schrieb Epposan:
> I have tried to run the 0.5.6 version using the image from
> [http://files.enerserve.eu/smartpi/2017-02-21_raspbian-jessie_smartpi.7z](u
> rl), but unfortunately get similar results.
> 
> Please see the attached log of events during the first login after having
> adjusted the filesystem running raspi-config. The initial `ps -ef` is
> executed only a few seconds after (re-)boot/login. The page at
> `<ip-adress>:1080` only gets a few updates before it remains static.
> 
> [smartpireadout-error-2.txt](https://github.com/nDenerserve/SmartPi/files/80
> 3057/smartpireadout-error-2.txt)


-- 
Mit freundlichen Grüßen

Jens Ramhorst

_______________________________

nD-enerserve GmbH
Göttinger Chaussee 12-14
30453 Hannover

Fon: +49 511 47 30 81 45
Fax: +49 511 47 30 81 48
Mail: j.ramhorst@enerserve.eu
Internet: www.enerserve.eu

USt.-IdNr.: DE303591409
Sitz der Gesellschaft: Hannover
Registergericht: Amtsgericht Hannover, HRB 213079
Geschäftsführer: Dipl.-Ing. Jens Ramhorst

**Comment by Epposan** [comment]
The smartpi has been made accessible via internet.
