### ISSUE TITLE
Non Intrusive Load Monitoring

### ISSUE THREAD

**Issue by joeblew99** [nDenerserve/SmartPi#16]
https://en.wikipedia.org/wiki/Nonintrusive_load_monitoring

This looks pretty good.
I was wondering if you are interested in machine learning aspects where you can detect all devices on the network and the energy usage of each ?

**Comment by StohanzlMart** [comment]
Yes it does! Though I doubt they are in the big data biz.

They don't even have a container (spell "docker") image.

Thus I imagine them being old neckbeards sitting around a windows server. 🙃
