### ISSUE TITLE
Webserver panic if adc_address is empty in smartpidc config

### ISSUE THREAD

**Issue by dandjo** [nDenerserve/SmartPi#184]
### Analysis

Ran into an error on my old SmartPi with the newest version. With an empty `/etc/smartpidc` the webserver exits with a panic. The panic is caused by following commit. The initialisation of the default value for `adc_address` is broken.

[fixed error in calibration function](https://github.com/nDenerserve/SmartPi/commit/88c141412e650e4d53c2504ae2ee6729a9a4204d)

### The error
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/nDenerserve/SmartPi/repository/config.(*DCconfig).ReadDCParameterFromFile(0x154c000)
	/home/pi/SmartPi/src/repository/config/smartpidcconfig_file.go:177 +0x3818
github.com/nDenerserve/SmartPi/repository/config.NewDCconfig(...)
	/home/pi/SmartPi/src/repository/config/smartpidcconfig_file.go:400
main.main()
	/home/pi/SmartPi/src/server/server.go:202 +0x54
```

### Workaround
The error is gone when adding following config value in `/etc/smartpidc`.

```
[device]
adc_address                = "0x6e"
```

**Comment by nD-enerserve** [comment]
Fixed :-)
