### ISSUE TITLE
Bug: current and power values are always 0.

### ISSUE THREAD

**Issue by Trickx** [nDenerserve/SmartPi#27]
smartpireadout does not seem to handle current values and power values properly anymore.
The values are reported to be always 0 on the console when started manually.
The server and MQTT values confirm 0.
Voltages are and cos phi values are ok.

**Comment by SuperQ** [comment]
Did you forget to update the config file to enable current monitoring?

**Comment by SuperQ** [comment]
Probably worth fixing the config parser to error on missing entries, and/or enable those booleans by default.

Also, fix the config parser to actually use booleans and not ints. :-)

**Comment by Trickx** [comment]
My local "/etc/smartpi" contains all entries of the current repository.
measure_voltage_x=1
Which entries are new or have to be changed?

**Comment by SuperQ** [comment]
See the updated [config](https://github.com/nDenerserve/SmartPi/blob/master/config/etc/smartpi).

You need `measure_current_x=1`

**Comment by SuperQ** [comment]
I will make a PR tomorrow morning that will panic on missing config params.

**Comment by Trickx** [comment]
I think I missed the measure_current_x=1.
BTW, building takes ages.
Is there a way of doing "go install" with the sqlite stuff to speed up the build process?
If not, I will go back to "go get".

**Comment by Trickx** [comment]
Do you know I nice logging lib, whichs supports
- log rotation
- max file sizes
- multiple log handlers?
I found some, but don't want to waste time with testing them all.

**Comment by SuperQ** [comment]
The build is slow, especially on a pi.  I haven't investigated why. :-/

**Comment by SuperQ** [comment]
I prefer logging to stdout and letting systemd or similar deal with it.

**Comment by Trickx** [comment]
-> https://groups.google.com/forum/#!topic/golang-nuts/KexEyiy6PvA
If "github.com/mattn/go-sqlite3" is installed via "go get", the build takes not much time on my RPI3.

**Comment by Trickx** [comment]
Values are being shown again - sorry my fault.
This issue can be closed.

**Comment by SuperQ** [comment]
Try using make, it might speed things up for you.

**Comment by Trickx** [comment]
Nope, I'm using make.

**Comment by nD-enerserve** [comment]
The build process is always slow. Therefore, I use a crosscompiler. But that is also a lot slower than the native build on the PC, but faster than on the RaspberryPi.
I use this: https://releases.linaro.org/components/toolchain/binaries/latest-5/arm-linux-gnueabihf/gcc-linaro-5.4.1-2017.01-x86_64_arm-linux-gnueabihf.tar.xz

**Comment by SuperQ** [comment]
Using a gcc cross-compiler is unnecessary.  The go compiler includes a built-in cross-compiler.

For a Pi B (2/3), you can setup the [env](https://golang.org/doc/install/source#environment) like this
```
export GOARCH='arm'
export GOARM='7'
```

**Comment by nD-enerserve** [comment]
Yes, thats right. But some external c libraries and bindings (like rrdtool) doesn't work with the internal cross compiler.

**Comment by SuperQ** [comment]
Although, I just tried that, and it's [tricky](https://github.com/mattn/go-sqlite3/issues/384) due to the sqlite3 code.

**Comment by nD-enerserve** [comment]
Yes, for all c-bindings you need a gcc-crosscompiler.

**Comment by SuperQ** [comment]
It may be worth switching to a more go-native embedded database like [boltdb](https://github.com/boltdb/bolt) or [rocksdb](https://github.com/facebook/rocksdb/).  This would work much better than sqlite.

We're also splitting out the Prometheus [tsdb](https://github.com/prometheus/tsdb) so that it's more embeddable.

**Comment by Trickx** [comment]
If the discussion here is correct,
https://groups.google.com/forum/#!topic/golang-nuts/KexEyiy6PvA
then all dependencies are built each time.
In case of sqlite3 this is time comsuming.
If the dependencies are fetched via "go get" or afterwards installed with "go install",
sqlite3 is not re-compiled each time and smartpi is being built in some few seconds.

**Comment by SuperQ** [comment]
This can be closed, both the build and config have been fixed.

**Comment by luisgepeto** [comment]
Hello 
Im having the same issue. Starting the readouts and server from /ust/local/bin directory gives mi 0 values for current. I have already set the flag to measure current to both 1, 0, true and false but the values stay the same. I am wondering why this is, since I am toggling the flag to change the current direction but it doesnt look like its doing nothing. The values im getting are consistenly low i.e. :-0.04451526
I have also verified that the ct_type is configured correctly
Greetings
Luis.

**Comment by MrLaffer** [comment]
What kind of current do you measure? AC / DC? Is the process smartpireadout running?
ps -e | grep smartpi

**Comment by luisgepeto** [comment]
Hello 
I am measuring AC current. I can confirm that the smartpireadout process is running, doing ps -e | grep smartpi returns the following:
 
>   447 ?        00:00:00 smartpi_check_u
>   616 ?        00:00:00 smartpiserver
>   617 ?        00:00:03 smartpireadout

However, I created a custom client to continously poll the /api/all/all/now endpoint and the values I receive for phase 1 (to which my current transformer is hooked) are almost always like the following:

> Measurements for phase 1
> current: -0.037909284 A 
> power: -4.1700215 W
> current: -0.042463403 A
> power: -4.6709743 W

As you can see they are constantly negative and negligible in value. This pattern continues even though I toggle the change_current_direction flag (values remain negative) . When manually running the smartpireadout process I get the following logs:

> DEBU[0000] Start SmartPi readout
> DEBU[0000] Connecting to MQTT broker at mymqtthost.com:1883
> DEBU[0000] Listening on :9246
> DEBU[0001] DeviceFetchInt: 1.562428ms cmd: 43c0 data: 000014e6 result: 5350
> DEBU[0001] DeviceFetchInt: 1.319463ms cmd: 43c2 data: 0000159b result: 5531
> DEBU[0001] DeviceFetchInt: 1.306494ms cmd: 43c4 data: 00001520 result: 5408
> DEBU[0001] DeviceFetchInt: 1.303889ms cmd: 43c6 data: 0000167d result: 5757
> DEBU[0001] DeviceFetchInt: 1.313785ms cmd: 43c1 data: 000014f4 result: 5364
> DEBU[0001] DeviceFetchInt: 1.304672ms cmd: 43c3 data: 00001480 result: 5248
> DEBU[0001] DeviceFetchInt: 1.305921ms cmd: 43c5 data: 000014e2 result: 5346
> DEBU[0001] DeviceFetchInt: 1.035977ms cmd: e607 data: 09b1 result: 2481
> DEBU[0001] DeviceFetchInt: 1.034258ms cmd: e607 data: 0a28 result: 2600
> DEBU[0001] DeviceFetchInt: 1.032279ms cmd: e607 data: 0a34 result: 2612
> DEBU[0001] DeviceFetchInt: 1.313837ms cmd: e519 data: 00000003 result: 3
> DEBU[0001] DeviceFetchInt: 1.330504ms cmd: e51a data: 00000003 result: 3
> DEBU[0001] DeviceFetchInt: 1.294723ms cmd: e51b data: 00000003 result: 3
> DEBU[0001] DeviceFetchInt: 1.297171ms cmd: e516 data: ffffffff result: -1
> DEBU[0001] DeviceFetchInt: 1.298369ms cmd: e517 data: ffffffff result: -1
> DEBU[0001] DeviceFetchInt: 1.477378ms cmd: e518 data: ffffffff result: -1
> DEBU[0001] DeviceFetchInt: 1.29764ms cmd: e400 data: 00000000 result: 0
> DEBU[0001] DeviceFetchInt: 1.29665ms cmd: e400 data: 00000000 result: 0
> DEBU[0001] DeviceFetchInt: 1.311546ms cmd: e400 data: 00000000 result: 0
> DEBU[0001] ReadValues: 180.777524ms I1: -0.058552961372305735  I2: -0.05311804547056865  I3: -0.056811386110975616  I4: -0.046331907383316794  V1: 110  V2: 110  V3: 110  P1: -6.440825750953631  P2: -5.8429850017625515  P3: -6.249252472207318  COS1: 1  COS2: 1  COS3: 1  F1: 103.14262691377921  F2: 98.42368319876971  F3: 97.9716800612323  AVA: 3  BVA: 3  CVA: 3  AVAR: 1  BVAR: 1  CVAR: 1  PFA: 110.5930004112988  PFB: 100.32770139876288  PFC: 321.9107027356574  AWATTHR: 0  BWATTHR: 0  CWATTHR: 0
> INFO[0001] ## Shared File Update ## 2018-01-15 00:05:00 I1: -0.058552961372305735  I2: -0.05311804547056865  I3: -0.056811386110975616  I4: -0.046331907383316794  V1: 110  V2: 110  V3: 110  P1: -6.440825750953631  P2: -5.8429850017625515  P3: -6.249252472207318  COS1: 1  COS2: 1  COS3: 1  F1: 103.14262691377921  F2: 98.42368319876971  F3: 97.9716800612323
> DEBU[0001] Publishing readoputs via MQTT...
> DEBU[0001]   -> %!(EXTRA string=smartpi-309de8ae-4f91-45ee-bb82-4b6e14aa3a8e/I1, string=:, float64=-0.058552961372305735)
> DEBU[0002]   -> %!(EXTRA string=smartpi-309de8ae-4f91-45ee-bb82-4b6e14aa3a8e/I2, string=:, float64=-0.05311804547056865)
> DEBU[0002]   -> %!(EXTRA string=smartpi-309de8ae-4f91-45ee-bb82-4b6e14aa3a8e/I3, string=:, float64=-0.056811386110975616)
> DEBU[0002]   -> %!(EXTRA string=smartpi-309de8ae-4f91-45ee-bb82-4b6e14aa3a8e/I4, string=:, float64=-0.046331907383316794)
> DEBU[0002]   -> %!(EXTRA string=smartpi-309de8ae-4f91-45ee-bb82-4b6e14aa3a8e/V1, string=:, float64=110)
> DEBU[0002]   -> %!(EXTRA string=smartpi-309de8ae-4f91-45ee-bb82-4b6e14aa3a8e/V2, string=:, float64=110)
> DEBU[0002]   -> %!(EXTRA string=smartpi-309de8ae-4f91-45ee-bb82-4b6e14aa3a8e/V3, string=:, float64=110)
> DEBU[0002]   -> %!(EXTRA string=smartpi-309de8ae-4f91-45ee-bb82-4b6e14aa3a8e/P1, string=:, float64=-6.440825750953631)
> DEBU[0002]   -> %!(EXTRA string=smartpi-309de8ae-4f91-45ee-bb82-4b6e14aa3a8e/P2, string=:, float64=-5.8429850017625515)
> DEBU[0002]   -> %!(EXTRA string=smartpi-309de8ae-4f91-45ee-bb82-4b6e14aa3a8e/P3, string=:, float64=-6.249252472207318)
> DEBU[0002]   -> %!(EXTRA string=smartpi-309de8ae-4f91-45ee-bb82-4b6e14aa3a8e/COS1, string=:, float64=1)
> DEBU[0002]   -> %!(EXTRA string=smartpi-309de8ae-4f91-45ee-bb82-4b6e14aa3a8e/COS2, string=:, float64=1)
> DEBU[0002]   -> %!(EXTRA string=smartpi-309de8ae-4f91-45ee-bb82-4b6e14aa3a8e/COS3, string=:, float64=1)
> DEBU[0002]   -> %!(EXTRA string=smartpi-309de8ae-4f91-45ee-bb82-4b6e14aa3a8e/F1, string=:, float64=103.14262691377921)
> DEBU[0003]   -> %!(EXTRA string=smartpi-309de8ae-4f91-45ee-bb82-4b6e14aa3a8e/F2, string=:, float64=98.42368319876971)
> DEBU[0003]   -> %!(EXTRA string=smartpi-309de8ae-4f91-45ee-bb82-4b6e14aa3a8e/F3, string=:, float64=97.9716800612323)
> DEBU[0003] MQTT done.
> ERRO[0003] Sleep duration negative: -420.682639ms
> DEBU[0003] DeviceFetchInt: 1.324984ms cmd: 43c0 data: 00001577 result: 5495
> DEBU[0003] DeviceFetchInt: 1.310349ms cmd: 43c2 data: 0000162a result: 5674
> DEBU[0003] DeviceFetchInt: 1.306494ms cmd: 43c4 data: 00001583 result: 5507
> DEBU[0003] DeviceFetchInt: 1.309046ms cmd: 43c6 data: 00001573 result: 5491
> DEBU[0003] DeviceFetchInt: 1.308578ms cmd: 43c1 data: 000014c7 result: 5319
> DEBU[0003] DeviceFetchInt: 1.306703ms cmd: 43c3 data: 00001570 result: 5488
> DEBU[0003] DeviceFetchInt: 1.305973ms cmd: 43c5 data: 00001522 result: 5410
> DEBU[0003] DeviceFetchInt: 1.029675ms cmd: e607 data: 0f98 result: 3992
> DEBU[0003] DeviceFetchInt: 1.044779ms cmd: e607 data: 0a33 result: 2611
> DEBU[0003] DeviceFetchInt: 1.024727ms cmd: e607 data: 1080 result: 4224
> DEBU[0003] DeviceFetchInt: 1.308994ms cmd: e519 data: 00000003 result: 3
> DEBU[0003] DeviceFetchInt: 1.307536ms cmd: e51a data: 00000003 result: 3
> DEBU[0003] DeviceFetchInt: 1.323785ms cmd: e51b data: 00000003 result: 3
> DEBU[0003] DeviceFetchInt: 1.306442ms cmd: e516 data: ffffffff result: -1
> DEBU[0003] DeviceFetchInt: 1.322953ms cmd: e517 data: ffffffff result: -1
> DEBU[0003] DeviceFetchInt: 1.307692ms cmd: e518 data: ffffffff result: -1
> DEBU[0003] DeviceFetchInt: 1.307276ms cmd: e400 data: 00000000 result: 0
> DEBU[0003] DeviceFetchInt: 1.322275ms cmd: e400 data: 00000000 result: 0
> DEBU[0003] DeviceFetchInt: 1.320348ms cmd: e400 data: 00000000 result: 0
> DEBU[0003] ReadValues: 179.296187ms I1: -0.054199023218980444  I2: -0.048824161636599556  I3: -0.053838697302843165  I4: -0.05431913185769287  V1: 110  V2: 110  V3: 110  P1: -5.961892554087849  P2: -5.370657780025951  P3: -5.9222567033127484  COS1: 1  COS2: 1  COS3: 1  F1: 64.1121963436013  F2: 98.00918836140889  F3: 60.59171597633136  AVA: 3  BVA: 3  CVA: 3  AVAR: 1  BVAR: 1  CVAR: 1  PFA: 102.36941832943302  PFB: 92.21754803526763  PFC: 305.06653805762886  AWATTHR: 0  BWATTHR: 0  CWATTHR: 0
> DEBU[0003] Sleeping for 819.831949ms
>

**Comment by MrLaffer** [comment]
Hello, Luis,

I don't understand the problem now. You have no measuring current, so the readings are almost zero. The fact that they are not completely zero is due to the minor error. But at 100A measuring current, 30 mA is practically nothing.

Greetings Jens

**Comment by luisgepeto** [comment]
I have confirmed that the current values are now measured, I removed the jumpers that were specified in the user manual. Is this correct?
