### ISSUE TITLE
Reduction of build time on Raspberry Pi 3 from 5 mins to 20secs

### ISSUE THREAD

**Issue by Trickx** [nDenerserve/SmartPi#29]
```
git clone https://github.com/nDenerserve/SmartPi.git`
cd SmartPi/`
time make buildsmartpireadout
```
leads to 
```
real	4m55.299s
user	5m10.800s
sys	0m5.170s
```
**5 minutes for each build!**

After deletion of the vendor folder and "go getting" all dependencies it takes only:
```
time make buildsmartpireadout
real	0m15.283s
user	0m19.860s
sys	0m1.110s
```
**Down to 20 secs!**

Is there a way to handle sources with govendor AND avoid re-compilation of sqlite3 each time?

**Comment by SuperQ** [comment]
It should be possible, we don't generally have this issue with govendor code.  I can ask the build experts I know.

**Comment by SuperQ** [comment]
This can be closed, yay!
