### ISSUE TITLE
smartpireadout crashes with readoutpanic

### ISSUE THREAD

**Issue by Trickx** [nDenerserve/SmartPi#3]
```
pi@devcon:~ $ sudo smartpireadout
Start SmartPi readoutpanic: write /dev/i2c-1: input/output error

goroutine 1 [running]:
panic(0x244c10, 0x963b16e0)
	/usr/lib64/go/src/runtime/panic.go:500 +0x33c
smartpi.InitADE7878(0x964320c0, 0x0, 0x0, 0x0)
	/home/jens/share/Produkte/SmartPi/software/smartpi/src/smartpi/ade7878.go:114 +0x22c
main.main()
	/home/jens/share/Produkte/SmartPi/software/smartpi/src/main/readout.go:49 +0x1a0
```
The installation procedure according to http://blog.enerserve.eu/2016/06/15/smartpi-installation/ was followed.
I used the standard user "pi" instead of "jens".
The path /home/jens does not exist on my pi and was not created by the installation.
The path /home/jens is not mentioned within the config file located at /etc/smartpi.
It seems to be hardcoded somewhere...

**Comment by Trickx** [comment]
On my raspberry pi 1 one single i2c bus is present:

> pi@devcon:/dev $ i2cdetect -l
i2c-1	i2c       	20804000.i2c                    	I2C adapter

but unfortunately there is no smartpi being detected:

> pi@devcon:/dev $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --

**Comment by nD-enerserve** [comment]
Your server problem is the lack of communication between the SmartPi- 
Module and the Raspberry. I have tested your module before delivery, the 
I2C communication has worked. I therefore assume that the 
connection between SmartPi and Raspberry Pi does not working (broken 
Electric wire). 
i2cdetect has to be the following output:
0 1 2 3 4 5 6 7 8 9 a b c d e f 
00: -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- 38 -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --
There are two processes running on the RaspberryPi: 
smartpireadout and 
smartpiserver
Smartpireadout reads out the values via the i2c bus and writes them into 
/var/tmp/smartpi/values. The server read out the values from this file. 
If the file does not exist, there are no values from the SmartPi has been read out. 
Smartpireadout crashed when i2c connection is missing. 
Please check the cable connection between the SmartPi and the Raspberry Pi

**Comment by Trickx** [comment]
Solved. Can be closed.
