### ISSUE TITLE
unused values?

### ISSUE THREAD

**Issue by Trickx** [nDenerserve/SmartPi#31]
ade7878.go reads new values, which are not reported via MQTT, yet.
I order to implement it, I would like to confirm their meaning.

- My guess is:
 -- apparent power: AVA BVA and CVA
 -- reactive powers: AVAR, BVAR, and CVAR

- Are active powers currently reported as P1, P2 and P3?

- What is the meaning of PFA, PFB and PFC? Power factor?

**Comment by SuperQ** [comment]
Yes, it would be good to have better documentation for the output of the ReadValues() function.  For updating Prometheus I need to know which items are counters, gauges, and how they work.

**Comment by nD-enerserve** [comment]
Yes. PFA... is the power factor. 
Apparent power is AVA...
Reactive power is AVAR...

**Comment by nD-enerserve** [comment]
AVA,AVB,AVC and
AVAR,AVBR, AVCR are nor calibrated yet.

**Comment by SuperQ** [comment]
Can you also document which values are gauges and which are cumulative counters?  I need this for correctly translating metrics.

**Comment by nD-enerserve** [comment]
The power factor differs from cos phi for consumers with many harmonics. For consumers without harmonics the power factor are equal to cos phi.
