### ISSUE TITLE
Incorrect watt-hour counting

### ISSUE THREAD

**Issue by SuperQ** [nDenerserve/SmartPi#33]
In reading over the [datasheet](http://www.analog.com/media/en/technical-documentation/data-sheets/ADE7854_7858_7868_7878.pdf), I discovered that the current smartpi reader code incorrectly measures watt-hours.  The current code uses AWATT,BWATT,CWATT to measure instantaneous power output from each phase every 5 seconds and uses this to guess at the watt-hours consumed over that time period.

In reality, the code should use AWATTHR,BWATTHR,CWATTHR to correctly measure accumulated watt hours.

However, to do this correctly, we will need a configuration option to correctly adjust the phase configuration in the chip's config register.

See this snipit from the datasheet:
```
Energy Accumulation Modes
The active power accumulated in each watt-hour accumulation
32-bit register (AWATTHR, BWATTHR, CWATTHR,
AFWATTHR, BFWATTHR, and CFWATTHR) depends on the
configuration of Bit 5 and Bit 4 (CONSEL bits) in the ACCMODE
register. The various configurations are described in Table 15.

Table 15. Inputs to Watt-Hour Accumulation Registers
CONSEL AWATTHR  BWATTHR       CWATTHR
00     VA × IA  VB × IB       VC × IC
01     VA × IA  0             VC × IC
10     VA × IA  VB × IB       VC × IC
                VB = −VA − VC
11     VA × IA  VB × IB       VC × IC
                VB = −VA

Depending on the polyphase meter service, choose the appropriate
formula to calculate the active energy. The American
ANSI C12.10 standard defines the different configurations of
the meter. Table 16 describes which mode to choose in these
various configurations.

Table 16. Meter Form Configuration
ANSI Meter Form Configuration CONSEL
5S/13S          3-wire delta  01
6S/14S          4-wire wye    10
8S/15S          4-wire delta  11
9S/16S          4-wire wye    00

Bits[1:0] (WATTACC[1:0]) in the ACCMODE register determine
how the CF frequency output can be generated as a function of
the total and fundamental active powers. Whereas the watt-hour
accumulation registers accumulate the active power in a signed
format, the frequency output can be generated in signed mode
or in absolute mode as a function of the WATTACC[1:0] bits.
See the Energy-to-Frequency Conversion section for details.
```

**Comment by Epposan** [comment]
We also need to set/calibrate all 48-bit xxxTHR registers (via the combined xxxTHR1 and xxxTHR0 registers) to set the LSB resolution of the various xxxHR power accumulator registers (ref: page 50 of the datasheet)

**Comment by SuperQ** [comment]
@Epposan Thanks for the tip, I guess I need to understand more about these config registers/calibrations to make it work.. I've got some experimental code that dumps the data, but doesn't do anything with it yet.

**Comment by MrLaffer** [comment]
Hello,

it is not so easy to calibrate the registers in the ADE7878. At high transmission ratios (in the case of the SmartPi ca 2000), the values are wrong. As with the register for the current, it must be calibrated to a different ratio and multiplied by an external constant. So far I have not received any reasonable values. The application note AN-1076 (http://www.analog.com/media/en/technical-documentation/application-notes/AN-1076.pdf) has not really brought me up yet.
Therefore, I first went the way, it over the achievement and the 5 seconds periods to make.

**Comment by jhardy08** [comment]
Hello,

I have just setup a SmartPi. Power reading are corrects but watt-hour are wrong. Any help ?

Thanks in advance,
Julien
