### ISSUE TITLE
smartpiserver crashes when accessed via browser

### ISSUE THREAD

**Issue by Trickx** [nDenerserve/SmartPi#4]
`pi@devcon:~ $ smartpiserver &
[1] 705
pi@devcon:~ $ SmartPi server started
2016/11/09 21:26:50 open /var/tmp/smartpi/values: no such file or directory`

When the smartpiserver is started manually is ir running until the first access of an browser.
When the browser accesses the smartpi server it dies with `/var/tmp/smartpi/values: no such file or directory` error.
This may be an consecutive fault caused by smartpireadout also crashing without creating 
`/var/tmp/smartpi/values`

**Comment by nD-enerserve** [comment]
See: https://github.com/nDenerserve/SmartPi/issues/3
