### ISSUE TITLE
Remove readout shared file Sync()

### ISSUE THREAD

**Issue by SuperQ** [nDenerserve/SmartPi#50]
In testing timings for the readout loop, I found that the [Sync()](https://github.com/nDenerserve/SmartPi/blob/master/src/readout/files.go#L53) causes an extra 15ms spent in the update loop.  This isn't much, but a `Close()` should be sufficient to convince the Linux kernel to make sure the file is up to date in memory for other apps to read.

I tried removing it, (now file write takes 0.2ms), and I still see the dynamic 5s updates on the smartpi server web UI.

The important thing I found was that it reduces the number of write IOPs on my Pi by about 30/min.  This isn't much, but should reduce the wear on my MicroSD card.

I think this `Sync()` call can be removed safely.

**Comment by Trickx** [comment]
The amount of write cycles is an important issue to keep in mind.
I lost already one SD card from an RPI 24/7 system.
This is why I'm using a read-only system these days: emonSD.
https://github.com/openenergymonitor/emonpi/wiki/emonSD-pre-built-SD-card-Download-&-Change-Log

The data storage makes use of redis, an in-memory database cache, to reduce write cycles.
https://redis.io/
EMONCMS is my preferred frontend.

Therefore, I'm thinking about forking readout.go and reducing it to the minimum:
Just reading the ADE7878 and feeding the data towards MQTT: no write access to SD at all.
I don't need an additional database, webserver or whatever.

Alternatively, readout.go will provide configuration capabilities to achieve the same in the future.
We will see...

**Comment by SuperQ** [comment]
Same reason I use Prometheus to scrape the metrics endpoint. :-)

I can add some more enable/disable flags to make the readout server no require write access.

We can also change the default to write to a tmpfs location and not the real filesystem.

**Comment by SuperQ** [comment]
Fixed via https://github.com/nDenerserve/SmartPi/pull/52
