### ISSUE TITLE
Add CI pipeline

### ISSUE THREAD

**Issue by SuperQ** [nDenerserve/SmartPi#55]
It would be nice to integrate a CI pipeline into the SmartPi repo.  This would allow us to have automated testing for commits and pull requests.

I don't have any preferences, BuildKite, CircleCI, Travis all work well.

**Comment by nD-enerserve** [comment]
OK. But I have to get involved. That takes a while.

**Comment by nD-enerserve** [comment]
Hi,

I get the foloowing error:

Build-agent version 0.0.4732-ed067b9 (2018-03-08T14:07:04+0000)
Configuration errors: 1 error occurred:

* Cannot find a job named `build` to run in the `jobs:` section of your configuration file.
If you expected a workflow to run, check your config contains a top-level key called 'workflows:'


Can you help?

**Comment by SuperQ** [comment]
I looked at the build pipleine (https://circleci.com/gh/nDenerserve/SmartPi), it looks like there might be something up with the vendoring.  Once Circle is configured in the project [webhooks](https://github.com/nDenerserve/SmartPi/settings/hooks), I can try and build a PR that will fix this.

**Comment by MrLaffer** [comment]
That would be nice.


Am 12.03.18 um 14:39 schrieb Ben Kochie:

**Comment by SuperQ** [comment]
Let me know when the webhook is configured.

**Comment by MrLaffer** [comment]
The webhook is configured


Am 12.03.18 um 14:56 schrieb Ben Kochie:

**Comment by SuperQ** [comment]
It looks like Circle is still not picking up pull requests into the pipeline.

**Comment by SuperQ** [comment]
It still looks like circle is not picking up the "pull request" webhook signals.  The good news is, I figured out what the build bug was.  PR for that shortly.

**Comment by SuperQ** [comment]
We now have a working CI pipeline, yay!
