### ISSUE TITLE
Version 0.6.1 shows power as a negative number

### ISSUE THREAD

**Issue by sarnau** [nDenerserve/SmartPi#57]
All power is now negative:

Power -3745.18 W
P1: -3189.71 W
P2: -438.91 W
P3: -116.56 W

Everything else seems fine

**Comment by nD-enerserve** [comment]
Please change the current direction.

Set parameter from 0 to 1 in /etc/smartpi or in the webinterface.

**Comment by sarnau** [comment]
I've never had faster service than with you. Wow!

Still not sure why this was triggered by the update, but it fixed it.

**Comment by SuperQ** [comment]
The update fixed a bunch of the config file defaults handling.
