### ISSUE TITLE
Serial number in configuration file

### ISSUE THREAD

**Issue by dstreppa** [nDenerserve/SmartPi#63]
Hi,
I noticed that serial number is configurable in /etc/smartpi, as below:
<pre>
pi@smartpi:~ $ cat /etc/smartpi 
[base]
serial                 = 00000000f66e70e8
name                   = House
..........
umts_username = ""
umts_password = ""
</pre>

In my opinion the presence of serial number in the conf file is potentially dangerous. First at all `root` is able to edit and change the serial number.
Moreover I noted that after an update via apt-get the serial number was re-set to the default.

**Comment by SuperQ** [comment]
The serial number is simply used for display purpose, there is no actual serial number assigned to the device that I'm aware of.
