### ISSUE TITLE
Incorrect initialisation of DICOEFF register

### ISSUE THREAD

**Issue by Trickx** [nDenerserve/SmartPi#64]
I don't know whether this relevant for the SmartPi to function,
but the register DICOEFF is not initialised properly:
 
current code:
```
// 0x43B5 (DICOEFF-REGISTER)
err = WriteRegister(d, "DICOEFF", 0xFF, 0x80, 0x00)
if err != nil {
	panic(err)
}
```

Data sheet:
... The DICOEFF 24-bit signed register is used in the digital integrator algorithm. At power-up or after a reset, its value is 0x000000. Before turning on the integrator, this register must be initialized with 0xFFF8000. As stated in the Current Waveform Gain Registers section, the serial ports of the ADE7878 work on 32-, 16-, or 8-bit words. Similar to the registers shown in Figure 35, the DICOEFF 24-bit signed register is accessed as a 32-bit register with four MSBs padded with 0s and sign extended to 28 bits, which practically means it is transmitted equal to 0xFFF8000...

proposed code:
```
// 0x43B5 (DICOEFF-REGISTER)
err = WriteRegister(d, "DICOEFF", 0x0F, 0xFF, 0x80, 0x00)
if err != nil {
	panic(err)
}
```

**Comment by petmag90** [comment]
I stumbled into this bug today. Whould have been nice if it was fixed. It is just a typo, but renders the integrator useless.
This is needed to use Rogowski coils.

**Comment by nD-enerserve** [comment]
Fixed
