### ISSUE TITLE
Different initialisation values for AVGAIN/BVGAIN/CVGAIN

### ISSUE THREAD

**Issue by Trickx** [nDenerserve/SmartPi#65]
Is there a reason to initialise AVGAIN/BVGAIN/CVGAIN with different values?
Furthermore, the values do not match instructioins from the data sheet:

> ...the AVGAIN, BVGAIN, and CVGAIN registers are accessed as 32-bit registers with four MSBs padded with 0s and sign extended to 28 bits. ...

current code
```
        // 0x4381 (AVGAIN-REGISTER)
	err = WriteRegister(d, "AVGAIN", 0xFF, 0xFC, 0x1C, 0xC2)
	if err != nil {
		panic(err)
	}

	// 0x4383 (BVGAIN-REGISTER)
	err = WriteRegister(d, "BVGAIN", 0xFF, 0xFB, 0xCA, 0x60)
	if err != nil {
		panic(err)
	}

	// 0x4385 (CVGAIN-REGISTER)
	err = WriteRegister(d, "CVGAIN", 0xFF, 0xFC, 0x12, 0xDE)
	if err != nil {
		panic(err)
	}
```
Register's values MSB equal to 0xF instead of 0x0.
I don't know whether this is correct or not, but all register values are negative,
since bits [27..23] equal to 1, see below.

<img width="281" alt="bildschirmfoto 2017-09-12 um 20 35 51" src="https://user-images.githubusercontent.com/8447808/30342377-03898716-97fa-11e7-8ea3-c0ba8e5b58fe.png">

**Comment by MrLaffer** [comment]
I think that was from the prototype board with different contact resistance in the voltage divider. Now its fixed and the measurements are better.
