### ISSUE TITLE
Non-unique client id in mqtt addon (with solution)

### ISSUE THREAD

**Issue by lmaertin** [nDenerserve/SmartPi#66]
Hey,

I'm using 4 smartpis with mqtt communication in one network. I had issues with the mqtt addon, because each client is named "SmartPi". This results in endless forced disconnections, message drops and a process load of about 80% CPU on the broker. In addition, it's impossible to distinguish between the different senders...
 
I managed to fix both issues by simply using the changeable **serial** variable from the smartpi parameters as client id. If you like that feature for operation with 2+ smartpis, feel free to put my changed code below in the next release:

In function `func newMQTTClient(c *smartpi.Config) (mqttclient MQTT.Client)` change `opts.SetClientID("SmartPi")`  to `opts.SetClientID(c.Serial)`.

Edit:
Of course, it may makes more sense to put an extra field in the mqtt config, but I was looking for a non-inversive solution here. I guess, a serial should be unique from default --- something that is not valid for the current smartpi implementation, but the user can change that identier with ease ;-)

**Comment by luisgepeto** [comment]
Is this issue closed? When will this be included in the next software version?

**Comment by SuperQ** [comment]
Sorta, maybe, the update was merged before the original author finished the idea.  I guess we need another PR to cleanup the change.

**Comment by lmaertin** [comment]
For me both (serial and name) is fine. At least it is sufficient when the client id is just unique. I guess, @SuperQ fixed everything now. Thanks for your assistance!
