### ISSUE TITLE
 Erratic Current measurements

### ISSUE THREAD

**Issue by luisgepeto** [nDenerserve/SmartPi#77]
I am not able of getting consistent current readings. 
I am using 4 different split core current transformers and attached them to the same cable that is powering up my pc so that ideally I have the same readings across all the SmartPi inputs. I am not measuring voltage and my RaspberryPi is powered up by a usb cable attached to the wall socket . Also the pins on my smartpi that are directly above my sensor inputs do not have any jumper installed except for I4 (not sure whether this is the correct installation)
I have also made sure that the contents of the file in /etc/smartpi have the following keys:

ct_type_1                  = YHDC_SCT013
ct_type_2                  = YHDC_SCT013
ct_type_3                  = YHDC_SCT013
ct_type_4                  = YHDC_SCT013
ct_type_1_primary_current  = 100
ct_type_2_primary_current  = 100
ct_type_3_primary_current  = 100
ct_type_4_primary_current  = 100

The two tests that I carried out were the following:
1. Make a full rotation of the connected current sensors connected to the smartpi i.e. I1 -> I2, I2 -> I3, I3 -> I4, I4-> I1 and so on. With this test I wanted to check if the result for each current sensor was consistent across inputs. 
2. Make a full rotation of the clamps on the target measurement without changing the sensors connection (should not affect measurement)

However once I start the smartpireadout program I am not able to get the same value for all four current transformers. 
Amongst the issues I have seen the following:
1. Measured current has differen values on every phase.
2. I4 input is the only one with the jumper installed on its jumper pins. This causes the reading to allways be a negative negligible value
3. The change_current_direction_X  flag doesnt change the current sign, doesnt matter if set to 0 or 1
4. Rotating the clamp position along the same conductor renders different current measurements (no idea why this is happening)

These are the results for my tests
========= CONNECTION ROTATION 1 =========            
I1: 1.6912797688692927  I2: 0.514815652681119  I3: 2.2674108816131033  I4: -0.05206709488183494

========= CONNECTION ROTATION 2 =========
I1: 0.06681043028378475  I2: 1.6093356501077427  I3: 0.5131641588988232  I4: -0.0834154495857771

========= CONNECTION ROTATION 3 =========
I1: 2.111149542648242  I2: 0.07515798067429807  I3: 1.6693899694639536  I4: -0.0578022823803531  

========= CONNECTION ROTATION 4 =========
I1: 0.4911242236950937  I2: 2.190541352837153  I3: 0.08903052844558285  I4: -0.05125636157052611  

========= CONNECTION ROTATION 5 (MATCHES CONNECTION ROTATION 1)/ CLAMP ROTATION 1 =========
I1: 1.3731720392394429  I2: 0.3151350408217172  I3: 2.119587174517789  I4: -0.06693053892249717   

========= CLAMP ROTATION 2 =========
I1: 2.0377931915546306  I2: 0.9799964104143295  I3: 2.0613945390616215  I4: -0.07572849670818207

========= CLAMP ROTATION 3 =========
I1: 1.1113652340060411  I2: 0.7465652710767372  I3: 2.000499459234423  I4: -0.07077401536129468  

========= CLAMP ROTATION 4 =========
I1: 1.0695674277341183  I2: 0.013782466292250427  I3: -0.004444019632359615  I4: -0.0753081164726886  

 ========= CLAMP ROTATION 5 =========
I1: 3.326889183695378  I2: 0.20892897704025812  I3: 0.46749284902842464  I4: -0.07894140279373937  

Do you have any idea why this is happening?
![jumper](https://user-images.githubusercontent.com/7987496/36854164-ea126da4-1d35-11e8-8d6f-5daf3cd23df4.jpg)
![sensor connection to smartpi](https://user-images.githubusercontent.com/7987496/36854165-eb8b9020-1d35-11e8-839a-b121e93fb29b.jpg)
![clamp connection to cable](https://user-images.githubusercontent.com/7987496/36854168-ed984aa2-1d35-11e8-8762-4f0a630929b9.jpg)

**Comment by red-gee** [comment]
Is this powercord with 2 or 3 lines inside p/n/pe?  You must not put the claps over all cables, only phase, otherwise you will get false readings
