### ISSUE TITLE
smartpireadout build fails due to extraneous swift bracket

### ISSUE THREAD

**Issue by Epposan** [nDenerserve/SmartPi#9]
sourcefile `src/smartpi/ade7878.go` contains an extraneous `}` on line 435 which prevents smartpireadout from being built.

**Comment by SuperQ** [comment]
This seems fixed.

**Comment by Epposan** [comment]
Right. It was fixed by TriCX end of november 2016 under the header 'Bugfixes from previous merge' and I am almost sure that it had been closed already without further comment.
