### ISSUE TITLE
How to install smartPi?

### ISSUE THREAD

**Issue by dominikstohl** [nDenerserve/SmartPi#91]
Hello,
I bought the smartpi and used it with the pre installed sd card -> everything works.
I needed to make some changes to the readout, so I followed the instructions in the readme.
After the go get command, I changed the files and then run the make command.
Everythink works fine, its compiled to 3 files. But how to run this now? I tried to use the commented out install script, but this doesnt work.
Can you please help me?!

Thanks! Dominik

**Comment by MrLaffer** [comment]
The easiest way is to exchange the files on the pre-installed SD card. The files can be found in the /usr/local/bin directory.

**Comment by dominikstohl** [comment]
Hey @MrLaffer,
tried your way and it didnt work. Compiled the latest code from git and replaced it and it didnt worked.
Which versions should I use?
Thanks! Dominik

**Comment by MrLaffer** [comment]
What ist the errormessage? Do you crosscompile?

**Comment by dominikstohl** [comment]
Hey @MrLaffer,
no, I am not cross compile, using your readme and makefile directly on a new installed Raspian OS.
There are no error messages, it compiles without errors.
If I replace the files and restart, there are just the placeholders for the values in the frontend and nothing is saved to the database.
Thanks for your help, Dominik

**Comment by MrLaffer** [comment]
Maybe your code's flawed, too. Can you please send me the changed source code and your compiled binaries (smartpi (at) enerserve (dot) eu)?
What did you change in the code?

**Comment by dominikstohl** [comment]
Hey Jens, I've sent you an email on 18.12.18, and today another one, are there further news on this topic?
Regards, Dominik

**Comment by GefaketHD** [comment]
Is there an update here? I find the instructions in the Readme to be both outdated and incomplete.
If I follow these instructions, I don't have a working SmartPi-setup afterwards. I would have to use the preinstalled smartpi-buster-version probably.
I would recommend adding an installable .deb for the pi, maybe as release in GitHub.
