### ISSUE TITLE
Add QoS to MQTT client

### ISSUE THREAD

**Issue by GammeI** [nDenerserve/SmartPi#93]
I'm wondering if its possible to add an option to change the default QoS option of the builtin MQTT client. 
I'm having problems with more than one smartpi collecting all the data at once from the broker. So if QoS enabled i would not get any data loss.

**Comment by robinsamuel** [comment]
How did you setup the MQTT?  Mine doesn't post any data

**Comment by G4mm3l** [comment]
I used the last version of smartpi and set up the MQTT settings in the webinterface panel. It worked out of the box.

**Comment by robinsamuel** [comment]
Thanks! I messed up the settings. Can I know where I can find the mqtt.go file?

**Comment by G4mm3l** [comment]
You have to compile your own version then. The source path is src/readout/mqtt.go .
If you want to edit the settings you can try to alter these directly in the file /etc/smartpi .
